### ISSUE TITLE
Design breaks in ultrawide resolution of 3440x1440

### ISSUE THREAD

**Issue by exsilium** [exsilium/cloud9#32]
Using cloud9 in ultrawide monitor in full screen mode the following is shown in Chrome:

![doesnotscalewide](https://user-images.githubusercontent.com/2134238/26969288-e5697c96-4d0d-11e7-89cf-0b5e20858ed7.png)

The following css is causing this:
```css
.tab_console .btncontainer {
       clip: rect(0px 3000px 30px 0px);
}
```
